<?php
/**
 * AccountConfigMinPayment
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Core API
 *
 * Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.
 *
 * The version of the OpenAPI document: 3.0.19
 * Contact: support@marqeta.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AccountConfigMinPayment Class Doc Comment
 *
 * @category Class
 * @description Contains configurations for a minimum payment override on a credit account, which overrides the minimum payment configurations on the associated credit product.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class AccountConfigMinPayment implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountConfigMinPayment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'active' => 'bool',
        'min_payment_flat_amount' => 'float',
        'min_payment_percentage' => 'float',
        'override_end_time' => '\DateTime',
        'override_start_time' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'active' => null,
        'min_payment_flat_amount' => null,
        'min_payment_percentage' => null,
        'override_end_time' => 'date-time',
        'override_start_time' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'active' => 'active',
        'min_payment_flat_amount' => 'min_payment_flat_amount',
        'min_payment_percentage' => 'min_payment_percentage',
        'override_end_time' => 'override_end_time',
        'override_start_time' => 'override_start_time'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'active' => 'setActive',
        'min_payment_flat_amount' => 'setMinPaymentFlatAmount',
        'min_payment_percentage' => 'setMinPaymentPercentage',
        'override_end_time' => 'setOverrideEndTime',
        'override_start_time' => 'setOverrideStartTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'active' => 'getActive',
        'min_payment_flat_amount' => 'getMinPaymentFlatAmount',
        'min_payment_percentage' => 'getMinPaymentPercentage',
        'override_end_time' => 'getOverrideEndTime',
        'override_start_time' => 'getOverrideStartTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['active'] = $data['active'] ?? null;
        $this->container['min_payment_flat_amount'] = $data['min_payment_flat_amount'] ?? null;
        $this->container['min_payment_percentage'] = $data['min_payment_percentage'] ?? null;
        $this->container['override_end_time'] = $data['override_end_time'] ?? null;
        $this->container['override_start_time'] = $data['override_start_time'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['min_payment_flat_amount']) && ($this->container['min_payment_flat_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_payment_flat_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['min_payment_percentage']) && ($this->container['min_payment_percentage'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_payment_percentage', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets active
     *
     * @return bool|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool|null $active Whether the minimum payment override is currently active.
     *
     * @return self
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets min_payment_flat_amount
     *
     * @return float|null
     */
    public function getMinPaymentFlatAmount()
    {
        return $this->container['min_payment_flat_amount'];
    }

    /**
     * Sets min_payment_flat_amount
     *
     * @param float|null $min_payment_flat_amount Flat amount of the minimum payment override.
     *
     * @return self
     */
    public function setMinPaymentFlatAmount($min_payment_flat_amount)
    {

        if (!is_null($min_payment_flat_amount) && ($min_payment_flat_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_payment_flat_amount when calling AccountConfigMinPayment., must be bigger than or equal to 0.');
        }

        $this->container['min_payment_flat_amount'] = $min_payment_flat_amount;

        return $this;
    }

    /**
     * Gets min_payment_percentage
     *
     * @return float|null
     */
    public function getMinPaymentPercentage()
    {
        return $this->container['min_payment_percentage'];
    }

    /**
     * Sets min_payment_percentage
     *
     * @param float|null $min_payment_percentage Percentage of the total statement balance used to calculate the minimum payment override amount.
     *
     * @return self
     */
    public function setMinPaymentPercentage($min_payment_percentage)
    {

        if (!is_null($min_payment_percentage) && ($min_payment_percentage < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_payment_percentage when calling AccountConfigMinPayment., must be bigger than or equal to 0.');
        }

        $this->container['min_payment_percentage'] = $min_payment_percentage;

        return $this;
    }

    /**
     * Gets override_end_time
     *
     * @return \DateTime|null
     */
    public function getOverrideEndTime()
    {
        return $this->container['override_end_time'];
    }

    /**
     * Sets override_end_time
     *
     * @param \DateTime|null $override_end_time Date and time when the minimum payment override ends, in UTC.
     *
     * @return self
     */
    public function setOverrideEndTime($override_end_time)
    {
        $this->container['override_end_time'] = $override_end_time;

        return $this;
    }

    /**
     * Gets override_start_time
     *
     * @return \DateTime|null
     */
    public function getOverrideStartTime()
    {
        return $this->container['override_start_time'];
    }

    /**
     * Sets override_start_time
     *
     * @param \DateTime|null $override_start_time Date and time when the minimum payment override starts, in UTC.
     *
     * @return self
     */
    public function setOverrideStartTime($override_start_time)
    {
        $this->container['override_start_time'] = $override_start_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


