<?php
/**
 * ApplicationResourceState
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Core API
 *
 * Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.
 *
 * The version of the OpenAPI document: 3.0.19
 * Contact: support@marqeta.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ApplicationResourceState Class Doc Comment
 *
 * @category Class
 * @description State of the application.  If manually &lt;&lt;/core-api/credit-applications#transitionApplication, transitioning an application state&gt;&gt;:  * &#x60;application_state&#x60; is the state to which you want to transition the application status; must be &#x60;ACCEPTED&#x60; or &#x60;REJECTED&#x60;. * &#x60;original_status&#x60; returns the state of the application before it was manually transitioned. * &#x60;status&#x60; returns the state to which the application was transitioned.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationResourceState
{
    /**
     * Possible values of this enum
     */
    const CREATED = 'CREATED';

    const DECISIONING = 'DECISIONING';

    const MANUAL_REVIEW = 'MANUAL_REVIEW';

    const EXPIRED = 'EXPIRED';

    const APPROVED = 'APPROVED';

    const REJECTED = 'REJECTED';

    const ACCEPTED = 'ACCEPTED';

    const DECLINED = 'DECLINED';

    const ERROR = 'ERROR';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED,
            self::DECISIONING,
            self::MANUAL_REVIEW,
            self::EXPIRED,
            self::APPROVED,
            self::REJECTED,
            self::ACCEPTED,
            self::DECLINED,
            self::ERROR
        ];
    }
}


