<?php
/**
 * RewardProgramsBalancesResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Core API
 *
 * Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.
 *
 * The version of the OpenAPI document: 3.0.19
 * Contact: support@marqeta.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RewardProgramsBalancesResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class RewardProgramsBalancesResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RewardProgramsBalancesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'billing_cycle_closing_date' => '\DateTime',
        'billing_cycle_opening_date' => '\DateTime',
        'net_balance' => 'float',
        'pending_reward_balance' => 'float',
        'percentage' => 'float',
        'reward_program_token' => 'string',
        'total_reward_balance' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'billing_cycle_closing_date' => 'date-time',
        'billing_cycle_opening_date' => 'date-time',
        'net_balance' => 'decimal',
        'pending_reward_balance' => 'decimal',
        'percentage' => 'decimal',
        'reward_program_token' => null,
        'total_reward_balance' => 'decimal'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'billing_cycle_closing_date' => 'billing_cycle_closing_date',
        'billing_cycle_opening_date' => 'billing_cycle_opening_date',
        'net_balance' => 'net_balance',
        'pending_reward_balance' => 'pending_reward_balance',
        'percentage' => 'percentage',
        'reward_program_token' => 'reward_program_token',
        'total_reward_balance' => 'total_reward_balance'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'billing_cycle_closing_date' => 'setBillingCycleClosingDate',
        'billing_cycle_opening_date' => 'setBillingCycleOpeningDate',
        'net_balance' => 'setNetBalance',
        'pending_reward_balance' => 'setPendingRewardBalance',
        'percentage' => 'setPercentage',
        'reward_program_token' => 'setRewardProgramToken',
        'total_reward_balance' => 'setTotalRewardBalance'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'billing_cycle_closing_date' => 'getBillingCycleClosingDate',
        'billing_cycle_opening_date' => 'getBillingCycleOpeningDate',
        'net_balance' => 'getNetBalance',
        'pending_reward_balance' => 'getPendingRewardBalance',
        'percentage' => 'getPercentage',
        'reward_program_token' => 'getRewardProgramToken',
        'total_reward_balance' => 'getTotalRewardBalance'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['billing_cycle_closing_date'] = $data['billing_cycle_closing_date'] ?? null;
        $this->container['billing_cycle_opening_date'] = $data['billing_cycle_opening_date'] ?? null;
        $this->container['net_balance'] = $data['net_balance'] ?? null;
        $this->container['pending_reward_balance'] = $data['pending_reward_balance'] ?? null;
        $this->container['percentage'] = $data['percentage'] ?? null;
        $this->container['reward_program_token'] = $data['reward_program_token'] ?? null;
        $this->container['total_reward_balance'] = $data['total_reward_balance'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['billing_cycle_closing_date'] === null) {
            $invalidProperties[] = "'billing_cycle_closing_date' can't be null";
        }
        if ($this->container['billing_cycle_opening_date'] === null) {
            $invalidProperties[] = "'billing_cycle_opening_date' can't be null";
        }
        if ($this->container['net_balance'] === null) {
            $invalidProperties[] = "'net_balance' can't be null";
        }
        if ($this->container['pending_reward_balance'] === null) {
            $invalidProperties[] = "'pending_reward_balance' can't be null";
        }
        if ($this->container['percentage'] === null) {
            $invalidProperties[] = "'percentage' can't be null";
        }
        if ($this->container['reward_program_token'] === null) {
            $invalidProperties[] = "'reward_program_token' can't be null";
        }
        if ((mb_strlen($this->container['reward_program_token']) > 36)) {
            $invalidProperties[] = "invalid value for 'reward_program_token', the character length must be smaller than or equal to 36.";
        }

        if ($this->container['total_reward_balance'] === null) {
            $invalidProperties[] = "'total_reward_balance' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets billing_cycle_closing_date
     *
     * @return \DateTime
     */
    public function getBillingCycleClosingDate()
    {
        return $this->container['billing_cycle_closing_date'];
    }

    /**
     * Sets billing_cycle_closing_date
     *
     * @param \DateTime $billing_cycle_closing_date Closing date of the billing cycle for which rewards were accrued, in UTC.
     *
     * @return self
     */
    public function setBillingCycleClosingDate($billing_cycle_closing_date)
    {
        $this->container['billing_cycle_closing_date'] = $billing_cycle_closing_date;

        return $this;
    }

    /**
     * Gets billing_cycle_opening_date
     *
     * @return \DateTime
     */
    public function getBillingCycleOpeningDate()
    {
        return $this->container['billing_cycle_opening_date'];
    }

    /**
     * Sets billing_cycle_opening_date
     *
     * @param \DateTime $billing_cycle_opening_date Opening date of the billing cycle for which rewards were accrued, in UTC.
     *
     * @return self
     */
    public function setBillingCycleOpeningDate($billing_cycle_opening_date)
    {
        $this->container['billing_cycle_opening_date'] = $billing_cycle_opening_date;

        return $this;
    }

    /**
     * Gets net_balance
     *
     * @return float
     */
    public function getNetBalance()
    {
        return $this->container['net_balance'];
    }

    /**
     * Sets net_balance
     *
     * @param float $net_balance The net balance for a billing cycle, which is total amount spent during a billing cycle, minus any refunds or reversals. Used to determine reward accrual.
     *
     * @return self
     */
    public function setNetBalance($net_balance)
    {
        $this->container['net_balance'] = $net_balance;

        return $this;
    }

    /**
     * Gets pending_reward_balance
     *
     * @return float
     */
    public function getPendingRewardBalance()
    {
        return $this->container['pending_reward_balance'];
    }

    /**
     * Sets pending_reward_balance
     *
     * @param float $pending_reward_balance The pending balance of the rewards accrued for the current billing cycle. Pending rewards cannot be redeemed.
     *
     * @return self
     */
    public function setPendingRewardBalance($pending_reward_balance)
    {
        $this->container['pending_reward_balance'] = $pending_reward_balance;

        return $this;
    }

    /**
     * Gets percentage
     *
     * @return float
     */
    public function getPercentage()
    {
        return $this->container['percentage'];
    }

    /**
     * Sets percentage
     *
     * @param float $percentage The reward percentage applied to the balance for the current billing cycle. Determined by the reward rules config.
     *
     * @return self
     */
    public function setPercentage($percentage)
    {
        $this->container['percentage'] = $percentage;

        return $this;
    }

    /**
     * Gets reward_program_token
     *
     * @return string
     */
    public function getRewardProgramToken()
    {
        return $this->container['reward_program_token'];
    }

    /**
     * Sets reward_program_token
     *
     * @param string $reward_program_token Unique identifier of reward program for which to return balances.
     *
     * @return self
     */
    public function setRewardProgramToken($reward_program_token)
    {
        if ((mb_strlen($reward_program_token) > 36)) {
            throw new \InvalidArgumentException('invalid length for $reward_program_token when calling RewardProgramsBalancesResponse., must be smaller than or equal to 36.');
        }

        $this->container['reward_program_token'] = $reward_program_token;

        return $this;
    }

    /**
     * Gets total_reward_balance
     *
     * @return float
     */
    public function getTotalRewardBalance()
    {
        return $this->container['total_reward_balance'];
    }

    /**
     * Sets total_reward_balance
     *
     * @param float $total_reward_balance The total balance of the rewards accrued to date minus the rewards redeemed to date.
     *
     * @return self
     */
    public function setTotalRewardBalance($total_reward_balance)
    {
        $this->container['total_reward_balance'] = $total_reward_balance;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


